document.writeln("<div class=\'g-wrap-top\'>");
document.writeln("					<div class=\'g-wrap\'>");
document.writeln("						<div class=\'g-bd3 s1 f-cb\'>");
document.writeln("							<div class=\'g-sd31\'>");
document.writeln("								<div class=\'date\'>2016年12月24日</div>");
document.writeln("							</div>");
document.writeln("							<div class=\'g-sd32\'>");
document.writeln("								<div class=\'iframe-weather\'><iframe name=\'weather_inc\' src=\'http://i.tianqi.com/index.php?c=code&amp;id=1\' width=\'230\' height=\'20\' frameborder=\'0\' marginwidth=\'0\' marginheight=\'0\' scrolling=\'no\' allowtransparency=\'true\' style=\'background-color=transparent\'></iframe></div>");
document.writeln("							</div>");
document.writeln("							<div class=\'g-mn3\'>");
document.writeln("								<div class=\'g-mn3c\'>");
document.writeln("									<div class=\'fn\'>");
document.writeln("										<!--已登录状态-->");
document.writeln("										<div class=\'tx\'>");
document.writeln("											<b><img src=\'asset/img/ps1/pic/tx.jpg\'></b><span>牛牛</span>");
document.writeln("											<div class=\'tx-menu\' style=\'display: none;\'>");
document.writeln("												<a href=\'javascript:void(0)\'><i class=\'js-img-bg-center\'><img src=\'asset/img/ps1/icon/ico-home1.png\'></i>我的主页</a>");
document.writeln("												<a href=\'javascript:void(0)\'><i class=\'js-img-bg-center\'><img src=\'asset/img/ps1/icon/ico-set.png\'></i>个人设置</a>");
document.writeln("												<a href=\'javascript:void(0)\' class=\'clbd\'><i class=\'js-img-bg-center\'><img src=\'asset/img/ps1/icon/ico-tuichudenglu.png\'></i>退出登录</a>");
document.writeln("											</div>");
document.writeln("										</div>");
document.writeln("										<!-- <span class=\'sch\'>");
document.writeln("											<button></button>");
document.writeln("											<input type=\'text\'>");
document.writeln("										</span> -->");
document.writeln("										<a href=\'javascript:void(0)\' class=\'ico ico-star\'>加入收藏 </a><s>|</s>");
document.writeln("										<a href=\'javascript:void(0)\' class=\'ico ico-wenti\'>问题反馈</a><s>|</s>");
document.writeln("										<!--未登录状态-->");
document.writeln("										<a href=\'javascript:void(0)\' class=\'ico ico-denglu\'>登录</a><s>|</s>");
document.writeln("										<a href=\'javascript:void(0)\'>注册</a>");
document.writeln("										");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");